E2Helper.Descriptions["base64encode"] = "Encode a string to base64."
E2Helper.Descriptions["base64decode"] = "Decode a string to base64."
E2Helper.Descriptions["base64encode"] = "Encode a string to base64."
E2Helper.Descriptions["base64decode"] = "Decode a string to base64."

E2Helper.Descriptions["isDoor"] = "Returns wether or not an entity is a door."
E2Helper.Descriptions["doorUnlock"] = "Unlocks a door."
E2Helper.Descriptions["doorLock"] = "Locks a door."
E2Helper.Descriptions["doorTitle"] = "Sets the title of a door."
E2Helper.Descriptions["doorOwner"] = "Returns the owner of a door"
E2Helper.Descriptions["doorOpened"] = "Returns wether or not a door is currently open."
E2Helper.Descriptions["doorLocked"] = "Returns wether or not a door is currently locked."
E2Helper.Descriptions["doorOpen"] = "Opens the door."
E2Helper.Descriptions["doorClose"] = "Closes the door."
E2Helper.Descriptions["doorUnlock"] = "Unlocks the door."
E2Helper.Descriptions["doorLock"] = "Locks the door."
E2Helper.Descriptions["doorCoOwners"] = "Returns a list of door Co-Owners. The index represents the player id."
E2Helper.Descriptions["doorAddCoOwner"] = "Returns a list of door Co-Owners. The index represents the player id."
E2Helper.Descriptions["doorRemoveCoOwner"] = "Removes specified door Co Owner"
E2Helper.Descriptions["doorRemoveCoOwners"] = "Removes all door Co Owners"

E2Helper.Descriptions["weaponType"] = "Returns the weapon class  of a spawned_weapon"